project:
  type: website
  output-dir: _site

website:
  title: "Yet Another TFG/TFM Handbook"
  # Opcional: subtítulo, portada, etc.

  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: docs/metodologia-agil.qmd
        text: Metodología ágil
      - href: docs/github-organizacion.qmd
        text: GitHub & organización
      - href: docs/memoria-tfg-tfm.qmd
        text: Memoria
      - href: docs/uso-responsable-ia.qmd
        text: Uso de la IA
      - text: TFG/TFM dirigidos
        menu:
          - href: tfgs/2024-2025/tempusugr/tempusugr-resumen.qmd
            text: 2024–2025 · TempusUGR
          - href: tfgs/2025-2026/pastillero-inteligente/pastillero-resumen.qmd
            text: 2025–2026 · Pastillero

format:
  html:
    toc: true
    theme: default
    include-in-header: fa.html
  pdf:
    toc: true
    number-sections: true
