# book/_quarto.yml
project:
  type: book
  # Hacemos que el libro se genere dentro de la web existente
  output-dir: ../_site/book

lang: es

book:
  title: "Yet Another TFG/TFM Handbook"
  author: "Juan Luis Jiménez Laredo"      # cámbialo por tu nombre
  date: "2025"
  # Opcional: subtítulo, portada, etc.
  subtitle: "Guía de trabajo para proyectos TFG/TFM en la ETSIIT - UGR"
  # cover-image: cover.png       # si algún día quieres una imagen de portada
  output-file: "handbook-tfg-tfm-etsiit-ugr"


  chapters:
    - index.qmd
    - ../docs/metodologia-agil.qmd
    - ../docs/github-organizacion.qmd
    - ../docs/memoria-tfg-tfm.qmd
    - ../docs/uso-responsable-ia.qmd

format:
  pdf:
    documentclass: scrbook   # aspecto de libro
    papersize: a4
    geometry:
      - top=25mm
      - bottom=25mm
      - inner=30mm
      - outer=20mm
    toc: true
    toc-title: "Índice"
    number-sections: true
    # keep-tex: true          # <- importante
    include-in-header: header.tex
    include-before-body:
      text: |
        %%% Override de colores de callout para que el fondo sea blanco
        % Note
        \definecolor{quarto-callout-note-color}{HTML}{D32F2F}
        \definecolor{quarto-callout-note-color-frame}{HTML}{D32F2F}
        % Warning
        \definecolor{quarto-callout-warning-color}{HTML}{F2994A}
        \definecolor{quarto-callout-warning-color-frame}{HTML}{F2994A}
        % Important
        \definecolor{quarto-callout-important-color}{HTML}{D32F2F}
        \definecolor{quarto-callout-important-color-frame}{HTML}{D32F2F}
        % Tip
        \definecolor{quarto-callout-tip-color}{HTML}{F2994A}
        \definecolor{quarto-callout-tip-color-frame}{HTML}{F2994A}
        % Caution
        \definecolor{quarto-callout-caution-color}{HTML}{D98A1A}
        \definecolor{quarto-callout-caution-color-frame}{HTML}{D98A1A}
        % Forzar que todas las tcolorbox tengan fondo opaco
        % Guardar las definiciones originales del entorno tcolorbox
        \let\OriginalTcolorbox\tcolorbox
        \let\OriginalEndTcolorbox\endtcolorbox

        % Redefinir el entorno tcolorbox para añadir SIEMPRE nuestras opciones al final
        \renewenvironment{tcolorbox}[1][]%
        {%
        % Llamamos al entorno original con:
        % - las opciones que venían (#1)
        % - y AL FINAL opacityback=1,colback=white, que sobreescriben las anteriores
        \OriginalTcolorbox[#1,opacityback=1,colback=white]%
        }%
        {%
        \OriginalEndTcolorbox
        }